### ISSUE TITLE
Fix social share items

### ISSUE THREAD

**Issue by DavidLemayian** [CodeForAfrica/TaxClock.Kenya#9]
They currently point to Code4SA images so probably needs a change of the `og:image` etc. Also there are **26** Facebook shares? Don't think that's happened.

Twitter handle should be `@Code4Africa` until Code for Kenya's becomes active.

**Comment by 4bic** [comment]
made some  [alterations to social buttons](https://github.com/CodeForAfrica/TaxClock.Kenya/pull/10)
